name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: '0 0 * * *' }]
  # Run automatically every time you push to main
  push: { branches: ['master', 'main'] }
  # Allows manual run
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to write to repo
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: SLajuwomi
          template: classic # Or use your own template/config
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago # Set your timezone
          plugins_errors_fatal: true
          # Add desired plugins here, mirroring the img URL or expanding
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_followup: yes
          plugin_followup_sections: user # Or repository
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_traffic: yes # Needs PAT with repo scope if used on private repos
