name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  update_quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Quote README
        uses: siddharth2016/quote-readme@main
